[package]
name = "NEruSt"
version = "0.0.0"
authors = ["Akourne Burschtein", "Mark McCaskey"]
edition = "2018"

[dependencies]
anyhow = "1"
sdl2 = {version = "0.34", features = ["bundled"], optional = true}
clap = "^2.31"

[features]
native-renderer = ["sdl2"]
default = ["native-renderer"]