[package]
name = "NEruSt"
version = "0.0.1"
authors = ["Akourne Burschtein", "Mark McCaskey"]

[features]
default = []
native = []

[dependencies]
#sdl2 = {version = "0.31", features = ["bundled"]}
clap = "*"
ezgl = { git = "https://github.com/Crocodoctogonopus/Ezgl" }
#stdweb = "*"
gleam = "*"
