[package]
name = "NEruSt"
version = "0.0.1"
authors = ["Akourne Burschtein", "Mark McCaskey"]

[features]
default = []
native = []

[dependencies]
#sdl2 = {version = "0.31", features = ["bundled"]}
clap = "^2.31"
gl = "^0.10.0"
ezgl = { git = "https://github.com/Crocodoctogonopus/Ezgl" }